// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApgTy6mBTMEqw0l40SS9imkdKxWcAx_4s',
    appId: '1:1087052790502:web:59beb2c0de7d7535649927',
    messagingSenderId: '1087052790502',
    projectId: 'tiktok-clone-jun',
    authDomain: 'tiktok-clone-jun.firebaseapp.com',
    storageBucket: 'tiktok-clone-jun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ_o_Lnq3jOPpPxJqQsSJQnEc-jFfyFCg',
    appId: '1:1087052790502:android:4b755e075f8cd5ca649927',
    messagingSenderId: '1087052790502',
    projectId: 'tiktok-clone-jun',
    storageBucket: 'tiktok-clone-jun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfOEbe8b8F8CbT4Qa_uCIDYERgXJDm_6Q',
    appId: '1:1087052790502:ios:ec198c2ab760f5c6649927',
    messagingSenderId: '1087052790502',
    projectId: 'tiktok-clone-jun',
    storageBucket: 'tiktok-clone-jun.appspot.com',
    iosClientId: '1087052790502-91698lmmaobviob4knalh4pirifb365l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
